print("Here is the original list:")
country = ['Tokyo', 'Nepal', 'Himalayas', 'United States', 'United Kingdom']
print(country)
print("\nHere is the sorted list:")
print(sorted(country))
print("\nHere is the original list again:")
print(country)
print("\nUsing reverse=True to change the list")
print(sorted(country,reverse=True))
print(country)
print("\nUsing reverse=True to change the list again")
country.reverse()
print(country)
country.reverse()
print(country)
print("\nUsing sort() to change the list to A-Z:")
country.sort
print(country)
country.sort(reverse=True)
print(country)
